---
deployment:
  tasks:
    - export DEPLOYPATH=/home/berandad/public_html/
    - /bin/cp -a public/. /home/berandad/pksoganilir.com/
    - /bin/cp -a public/. $DEPLOYPATH
    - /bin/chmod -R 775 storage bootstrap/cache
