---
deployment:
  tasks:
    - export DEPLOYPATH=/home/berandad/pksoganilir.com/
    - /bin/cp -a public/. $DEPLOYPATH
    - /bin/cp -a public/. /home/berandad/public_html/
    - /bin/mkdir -p storage/framework/sessions storage/framework/views storage/framework/cache storage/logs bootstrap/cache
    - /bin/chmod -R 775 storage bootstrap/cache
